services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY=super-secret-cyber-ueba-key-2026-antigravity
      - DATABASE_URL=sqlite:///./cyber_ueba.db
    restart: always

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: always
